services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: contact-book
    working_dir: /var/www/html
    ports:
      - "8000:80"
    networks:
      - contact-book-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: contact-book-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - contact-book-network

networks:
  contact-book-network:
    driver: bridge